	
	------------------------------------------------------------------------------------
	Help on DATA M FILES
    
    Also refer to the commented text at the top of the example data M file in, included 
    in the mapAnalysis3p0 directory.
    
    General information:
    
    - The data M file is a function, bearing the name of a cell/expt, that when called 
    from the command line or from another function generates a structure variable 
    containing various data fields.
    
    - Your data M files should reside in a directory that is on the Matlab path.

    - The data M files can now be auto-generated by the mapAnalysis software. They can
    of course still be made 'from scratch', or edited as desired. 
    
    - Call the function to retrieve the data -- e.g.:
        cellA = g0693P1; 
        imagesc(cellA.genMean);
    Tip: Check that you have correctly entered the data by running the function from the 
    command line, as in the example.
    
    Notes that are now largely obsolete:
    
    - The function's name is typically of the format 'x0000P1', a concatentation of user 
    initial ('x'), expt number ('0000'), and the amplifier channel ('P1'). Avoid spaces.
    
    - Enter the function's name in 3 places: the function name (first line), the help 
    line (second line), and the 'map.experiment' field (first data field).
    
    - Make sure after you paste in data that the last line in the data M file is still:
        out = map;
        
    Editing: 
    gs july 2005 -- modified
    
	------------------------------------------------------------------------------------
	
