classdef BasicEphysAnalysisGUI < handle
    properties(Constant=true)
        DataOptions = {                     ...
            'Raw Traces',                   ...
            'Baseline Subtracted Traces',   ...
            'Average Trace',                ...
            'Filtered Traces',              ...
            'Average Filtered Trace',       ...
            'Filtered Average Trace',       ...
            'Series Resistance',            ...
            'Input Resistance',             ...
            'Membrane Time Constant',       ...
            'Membrane Capacitance',         ...
            'Charge Transferred',           ...
            'Temporal Parameters',          ...
            };
    end
    
    properties(GetAccess=public,SetAccess=protected)
        Figure
        DataAxis
    end
    
    properties(Hidden=true)
        AllTraces
        TraceNames
        SelectedTraceIndices
    end
    
    properties
        SelectedTraces
        SelectedTraceNames
        Baseline
        BaselineSubtractedTraces
        AverageTrace
        FilteredTraces
        AverageFilteredTrace
        FilteredAverageTrace
        SeriesResistance
        InputResistance
        MembraneTimeConstant
        MembraneCapacitance
        SteadyStateCurrent
        ChargeTransferred
        Peaks
        PeakIndices
        Latencies
        RiseTimes
        FallTimes
        HalfWidths
        Peak10IndexRising
        Peak90IndexRising
        Peak90IndexFalling
        Peak10IndexFalling
        Peak50IndexRising
        Peak50IndexFalling
        SampleRate
        RecordingMode = 'IC'
        Filenames
    end
    
    methods
        function self = BasicEphysAnalysisGUI
            figureWidth = 800;
            figureHeight = 500;
            self.Figure = figure('Position',[100 100 figureWidth figureHeight]);
            
            % TODO : why doesn't Matlab have decent automatic layout
            % options?  like a fucking grid layout or something jesus fuck
            self.DataAxis = subplot('Position',[245/figureWidth 50/figureHeight 540/figureWidth 400/figureHeight]);
            
            uicontrol(self.Figure,                                  ...
                'Style',    'popupmenu',                            ...
                'String',   BasicEphysAnalysisGUI.DataOptions,      ...
                'Units',    'normalized',                           ...
                'Tag',      'dataselectionpopupmenu',               ...
                'Position', [245/figureWidth 460/figureHeight 540/figureWidth 25/figureHeight],       ...
                'Callback', @(varargin) self.refreshData()          ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'pushbutton',                           ...
                'String',   'Choose Files...',                      ...
                'Units',    'normalized',                           ...
                'Position', [10/figureWidth 465/figureHeight 85/figureWidth 25/figureHeight],        ...
                'Callback', @(varargin) self.loadFiles()            ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'pushbutton',                           ...
                'String',   'Choose Traces...',                      ...
                'Units',    'normalized',                           ...
                'Position', [100/figureWidth 465/figureHeight 85/figureWidth 25/figureHeight],        ...
                'Callback', @(varargin) self.openChooseTracesDialog()            ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'pushbutton',                           ...
                'String',   'Save Data...',                         ...
                'Units',    'normalized',                           ...
                'Position', [10/figureWidth 435/figureHeight 85/figureWidth 25/figureHeight],        ...
                'Callback', @(varargin) self.saveData()            ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'pushbutton',                           ...
                'String',   'Save Figure...',                       ...
                'Units',    'normalized',                           ...
                'Position', [100/figureWidth 435/figureHeight 85/figureWidth 25/figureHeight],        ...
                'Callback', @(varargin) self.saveFigure()            ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Preprocessing:',                       ...
                'Units',    'normalized',                           ...
                'Position', [10/figureWidth 410/figureHeight 120/figureWidth 25/figureHeight],        ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uibuttongroup(self.Figure,'Position',[10/figureWidth 270/figureHeight 175/figureWidth 150/figureHeight]);
            
            uicontrol(self.Figure,                                  ...
                'Style',    'checkbox',                             ...
                'String',   'Baseline Subtract',                    ...
                'Units',    'normalized',                           ...
                'Tag',      'baselinesubtractcheckbox',             ...
                'Position', [15/figureWidth 400/figureHeight 110/figureWidth 15/figureHeight],        ...
                'Callback', @(varargin) self.updatePreprocessing()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Start (s):',                           ...
                'Units',    'normalized',                           ...
                'Position', [15/figureWidth 380/figureHeight 60/figureWidth 15/figureHeight],         ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'edit',                                 ...
                'String',   '0',                                    ...
                'Units',    'normalized',                           ...
                'Tag',      'baselinestarteditbox',                 ...
                'Position', [60/figureWidth 380/figureHeight 30/figureWidth 15/figureHeight],         ...
                'Callback', @(varargin) self.updatePreprocessing()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Length (s):',                          ...
                'Units',    'normalized',                           ...
                'Position', [90/figureWidth 380/figureHeight 60/figureWidth 15/figureHeight],         ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'edit',                                 ...
                'String',   '0.1',                                  ...
                'Units',    'normalized',                           ...
                'Tag',      'baselinelengtheditbox',                ...
                'Position', [145/figureWidth 380/figureHeight 30/figureWidth 15/figureHeight],        ...
                'Callback', @(varargin) self.updatePreprocessing()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'checkbox',                             ...
                'String',   'Filter Before Averaging:',             ...
                'Units',    'normalized',                           ...
                'Tag',      'prefiltercheckbox',                    ...
                'Position', [15/figureWidth 360/figureHeight 150/figureWidth 15/figureHeight],        ...
                'Callback', @(varargin) self.updatePreprocessing()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'popupmenu',                            ...
                'String',   {                                       ...
                    'Mean',                                         ...
                    'Median'                                        ...
                    },                                              ...
                'Units',    'normalized',                           ...
                'Tag',      'prefilterpopupmenu',                   ...
                'Position', [15/figureWidth 330/figureHeight 75/figureWidth 25/figureHeight],         ...
                'Callback', @(varargin) self.updatePreprocessing()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Length:',                              ...
                'Units',    'normalized',                           ...
                'Position', [95/figureWidth 335/figureHeight 50/figureWidth 15/figureHeight],         ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'edit',                                 ...
                'String',   '3',                                    ...
                'Units',    'normalized',                           ...
                'Tag',      'prefiltereditbox',                     ...
                'Position', [140/figureWidth 335/figureHeight 40/figureWidth 15/figureHeight],        ...
                'Callback', @(varargin) self.updatePreprocessing()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'checkbox',                             ...
                'String',   'Filter After Averaging:',              ...
                'Units',    'normalized',                           ...
                'Tag',      'postfiltercheckbox',                   ...
                'Position', [15/figureWidth 315/figureHeight 150/figureWidth 15/figureHeight],        ...
                'Callback', @(varargin) self.updatePreprocessing()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'popupmenu',                            ...
                'String',   {                                       ...
                    'Mean',                                         ...
                    'Median'                                        ...
                    },                                              ...
                'Units',    'normalized',                           ...
                'Tag',      'postfilterpopupmenu',            ...
                'Position', [15/figureWidth 285/figureHeight 75/figureWidth 25/figureHeight],         ...
                'Callback', @(varargin) self.updatePreprocessing()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Length:',                              ...
                'Units',    'normalized',                           ...
                'Position', [95/figureWidth 290/figureHeight 50/figureWidth 15/figureHeight],         ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'edit',                                 ...
                'String',   '3',                                    ...
                'Units',    'normalized',                           ...
                'Tag',      'postfiltereditbox',                    ...
                'Position', [140/figureWidth 290/figureHeight 40/figureWidth 15/figureHeight],        ...
                'Callback', @(varargin) self.updatePreprocessing()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Cell Parameters Calculation:',       ...
                'Units',    'normalized',                           ...
                'Position', [10/figureWidth 240/figureHeight 180/figureWidth 25/figureHeight],        ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uibuttongroup(self.Figure,'Position',[10/figureWidth 150/figureHeight 175/figureWidth 100/figureHeight]);
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Using:',                               ...
                'Units',    'normalized',                           ...
                'Position', [15/figureWidth 225/figureHeight 35/figureWidth 15/figureHeight],         ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'popupmenu',                            ...
                'String',   BasicEphysAnalysisGUI.DataOptions(1:6), ...
                'Units',    'normalized',                           ...
                'Tag',      'rsdatasourcepopupmenu',                ...
                'Position', [50/figureWidth 230/figureHeight 130/figureWidth 15/figureHeight],        ...
                'Callback', @(varargin) self.updateCellParametersCalculation()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Voltage Step (V):',                    ...
                'Units',    'normalized',                           ...
                'Position', [15/figureWidth 200/figureHeight 100/figureWidth 15/figureHeight],        ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'edit',                                 ...
                'String',   '-5',                                   ...
                'Units',    'normalized',                           ...
                'Tag',      'voltagestepeditbox',                   ...
                'Position', [110/figureWidth 200/figureHeight 30/figureWidth 15/figureHeight],        ...
                'Callback', @(varargin) self.updateCellParametersCalculation()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Resp Start (s):',                      ...
                'Units',    'normalized',                           ...
                'Position', [15/figureWidth 175/figureHeight 90/figureWidth 15/figureHeight],         ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'edit',                                 ...
                'String',   '0',                                    ...
                'Units',    'normalized',                           ...
                'Tag',      'rsstarteditbox',                       ...
                'Position', [90/figureWidth 175/figureHeight 20/figureWidth 15/figureHeight],         ...
                'Callback', @(varargin) self.updateCellParametersCalculation()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Length (s):',                          ...
                'Units',    'normalized',                           ...
                'Position', [110/figureWidth 175/figureHeight 60/figureWidth 15/figureHeight],         ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'edit',                                 ...
                'String',   '0.1',                                  ...
                'Units',    'normalized',                           ...
                'Tag',      'rslengtheditbox',                      ...
                'Position', [165/figureWidth 175/figureHeight 20/figureWidth 15/figureHeight],        ...
                'Callback', @(varargin) self.updateCellParametersCalculation()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'SS Start (s):',                        ...
                'Units',    'normalized',                           ...
                'Position', [15/figureWidth 155/figureHeight 90/figureWidth 15/figureHeight],         ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'edit',                                 ...
                'String',   '0',                                    ...
                'Units',    'normalized',                           ...
                'Tag',      'ssstarteditbox',                       ...
                'Position', [90/figureWidth 155/figureHeight 20/figureWidth 15/figureHeight],         ...
                'Callback', @(varargin) self.updateCellParametersCalculation()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Length (s):',                          ...
                'Units',    'normalized',                           ...
                'Position', [110/figureWidth 155/figureHeight 60/figureWidth 15/figureHeight],         ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'edit',                                 ...
                'String',   '0.1',                                  ...
                'Units',    'normalized',                           ...
                'Tag',      'sslengtheditbox',                      ...
                'Position', [165/figureWidth 155/figureHeight 20/figureWidth 15/figureHeight],        ...
                'Callback', @(varargin) self.updateCellParametersCalculation()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Temporal Parameters Calculation:',     ...
                'Units',    'normalized',                           ...
                'Position', [10/figureWidth 120/figureHeight 180/figureWidth 25/figureHeight],        ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uibuttongroup(self.Figure,'Position',[10/figureWidth 75/figureHeight 175/figureWidth 55/figureHeight]);
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Using:',                               ...
                'Units',    'normalized',                           ...
                'Position', [15/figureWidth 105/figureHeight 35/figureWidth 15/figureHeight],         ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'popupmenu',                            ...
                'String',   BasicEphysAnalysisGUI.DataOptions(1:6), ...
                'Units',    'normalized',                           ...
                'Tag',      'tpdatasourcepopupmenu',                ...
                'Position', [50/figureWidth 110/figureHeight 130/figureWidth 15/figureHeight],        ...
                'Callback', @(varargin) self.updateTPCalculation()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Start (s):',                           ...
                'Units',    'normalized',                           ...
                'Position', [15/figureWidth 80/figureHeight 60/figureWidth 15/figureHeight],         ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'edit',                                 ...
                'String',   '0',                                    ...
                'Units',    'normalized',                           ...
                'Tag',      'tpstarteditbox',                       ...
                'Position', [60/figureWidth 80/figureHeight 30/figureWidth 15/figureHeight],         ...
                'Callback', @(varargin) self.updateTPCalculation()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Length (s):',                          ...
                'Units',    'normalized',                           ...
                'Position', [90/figureWidth 80/figureHeight 60/figureWidth 15/figureHeight],         ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'edit',                                 ...
                'String',   '0.1',                                  ...
                'Units',    'normalized',                           ...
                'Tag',      'tplengtheditbox',                      ...
                'Position', [145/figureWidth 80/figureHeight 30/figureWidth 15/figureHeight],        ...
                'Callback', @(varargin) self.updateTPCalculation()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Recording Mode:',                      ...
                'Units',    'normalized',                           ...
                'Position', [10/figureWidth 45/figureHeight 180/figureWidth 25/figureHeight],         ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            recordModeButtonGroup = uibuttongroup(self.Figure,      ...
                'Position', [10/figureWidth 20/figureHeight 175/figureWidth 35/figureHeight],         ...
                'SelectionChangedFcn',  @(~,eventData,varargin) self.updateRecordingMode(eventData)  ...
                );
            
            uicontrol(recordModeButtonGroup,                        ...
                'Style',    'radiobutton',                          ...
                'String',   'IC',                                   ...
                'Tag',      'currentclampradiobutton',              ...
                'Units',    'normalized',                           ...
                'Position', [5/175 5/35 75/175 25/35],              ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uicontrol(recordModeButtonGroup,                        ...
                'Style',    'radiobutton',                          ...
                'String',   'VC',                                   ...
                'Units',    'normalized',                           ...
                'Position', [95/175 5/35 75/175 25/35],             ...
                'HorizontalAlignment',  'left'                      ...
                );
            
%             uipanel(self.Figure,               ...
%                 'BackgroundColor',  'w',                            ...
%                 'Tag',      'filelistouterpanel',                   ...
%                 'Position', [800/figureWidth 10/figureHeight 190/figureWidth 480/figureHeight]);
%             
%             uipanel(self.Figure,               ...
%                 'BackgroundColor',  'w',                            ...
%                 'BorderType',       'none',                         ...
%                 'Tag',      'filelistinnerpanel',                   ...
%                 'Position', [830/figureWidth 22/figureHeight 158/figureWidth 464/figureHeight]);
%             
%             uicontrol(recordModeButtonGroup,                        ...
%                 'Style',    'slider',                               ...
%                 'Value',    0,                                      ...
%                 'Units',    'normalized',                           ...
%                 'Position', [800/figureWidth 5/35 75/175 25/35]             ...
%                 );
        end
        
        function delete(self)
            delete(self.Figure)
        end
        
        function chooseTraces(self,fig)
            controls = self.getTraceChoiceUIControls(fig);
            
            if isempty(controls)
                errordlg('Something went wrong.  Close the Choose Traces... dialog and try again.');
                return
            end
            
            switch get(controls(1),'Style')
                case 'slider'
                    errordlg('Not yet!!!');
                case 'checkbox'
                    selectedTraceIndices = self.chooseTracesUsingCheckboxes(controls);
                otherwise
                    errordlg('Something went wrong.  Close the Choose Traces... dialog and try again.');
                    return
            end
            
            self.SelectedTraceIndices = selectedTraceIndices;
            self.SelectedTraces = self.AllTraces(:,self.SelectedTraceIndices);
            self.SelectedTraceNames = self.TraceNames(1,self.SelectedTraceIndices);
            
            close(fig)
            
            self.updatePreprocessing();
        end
        
        function selectedTraceIndices = chooseTracesUsingCheckboxes(self,boxes) 
            if numel(boxes) == 1
                selectedTraceIndices = find(get(boxes,'Value'));
                return
            end
            
            % TODO : is flipud always right?  better to pull the index out
            % of the tag
            selectedIndices = find(flipud(cell2mat(get(boxes,'Value'))));
            
            firstTag = get(boxes(1),'Tag');
            
            if firstTag(1) == 't'
                selectedTraceIndices = selectedIndices;
                return
            end
            
            if firstTag(1) == 'c'
                colIndices = repmat((1:size(self.AllTraces,2))',numel(selectedIndices),1);
                pagIndices = kron(selectedIndices,ones(size(self.AllTraces,2),1));
            elseif firstTag(1) == 's'
                colIndices = repmat(selectedIndices,size(self.AllTraces,3),1);
                pagIndices = kron((1:size(self.AllTraces,3))',ones(numel(selectedIndices),1));
            else
                % TODO : better error handling/logging
                errordlg('Something went wrong.  Close the Choose Traces... dialog and try again.');
                return
            end

            if isempty(colIndices) || isempty(pagIndices)
                selectedTraceIndices = [];
            else
                selectedTraceIndices = sub2ind([size(self.AllTraces,2) size(self.AllTraces,3)],colIndices,pagIndices);
            end
        end
        
        function loadFiles(self)
            [filenames,pathname] = uigetfile('*.xsg;*.h5','MultiSelect','on'); % TODO : will we ever want to combine files from multiple folders?  Might make sense to switch to uipickfiles
    
            if isnumeric(filenames)
                return
            end

            if ischar(filenames)
                filenames = {filenames};
            end
            
            self.Filenames = cellfun(@(s) sprintf('%s%s',pathname,s),filenames,'UniformOutput',false);
    
            [self.AllTraces,self.SampleRate,self.TraceNames] = concatenateTraces(self.Filenames);
            
            self.SelectedTraceIndices = 1:(size(self.AllTraces,2)*size(self.AllTraces,3));
            
            self.SelectedTraces = self.AllTraces(:,self.SelectedTraceIndices);
            
            self.SelectedTraceNames = self.TraceNames(self.SelectedTraceIndices);
            
            for ii = 1:numel(self.TraceNames)
                disp(self.TraceNames{ii});
            end
            
            self.updatePreprocessing();
        end
        
        function openChooseTracesDialog(self)
            if ~iscell(self.TraceNames)
                warndlg('No traces to choose from.  Try loading some files first.');
                return
            end
            
            [~,longestStringIndex] = max(cellfun(@numel,self.TraceNames));
            
            longestString = self.TraceNames(longestStringIndex);
            
            fig = figure('Visible','off');
            h = uicontrol('Style','text','String',longestString,'Visible','off');
            longestStringPixels = get(h,'Extent');
            longestStringPixels = longestStringPixels(3);
            close(fig);
            
            figureWidth = max(20+10*4+100*3,20+50+20+longestStringPixels);
            figureHeight = 20+50+10+5+30*max(2,min(10,max([numel(self.TraceNames) size(self.AllTraces,2) size(self.AllTraces,3)])))+30;
            
            chooseTracesFigure = figure('Units','pixels','Position',[100 100 figureWidth figureHeight]);
            
            choiceModeButtonGroup = uibuttongroup(chooseTracesFigure,           ...
                'Units',                'pixels',                               ...
                'Position',             [10 figureHeight-60 figureWidth-20 50]  ...
                );
            
            uicontrol(choiceModeButtonGroup,...
                'Style',                'text',                          ...
                'Units',                'pixels',                               ...
                'Position',             [5 30 200 15],             ...
                'HorizontalAlignment',  'left',                     ...
                'String',               'Choose Traces By:'                        ...
                );
            
            uicontrol(choiceModeButtonGroup,...
                'Style',                'radiobutton',                          ...
                'Units',                'pixels',                               ...
                'Position',             [10 5 100 25],             ...
                'String',               'Trace Name',                        ...
                'Value',                true,             ...
                'Callback',             @(varargin) self.createAllTracesChoicePanel(chooseTracesFigure)   ...
                );
            
            uicontrol(choiceModeButtonGroup,...
                'Style',                'radiobutton',                          ...
                'Units',                'pixels',                               ...
                'Position',             [120 5 100 25],            ...
                'String',               'Sweep Number',                      ...
                'Value',                false,                      ...
                'Callback',             @(varargin) self.createSweepsChoicePanel(chooseTracesFigure)   ...
                );
            
            uicontrol(choiceModeButtonGroup,...
                'Enable',               'on',               ...
                'Style',                'radiobutton',                          ...
                'Units',                'pixels',                               ...
                'Position',             [230 5 100 25],            ...
                'String',               'Channel Name',                           ...
                'Value',                false,      ...
                'Callback',             @(varargin) self.createChannelsChoicePanel(chooseTracesFigure)   ...
                );
            
            uibuttongroup(chooseTracesFigure,'Units','pixels','Position',[10 40 figureWidth-20 figureHeight-110]);
            
            self.createAllTracesChoicePanel(chooseTracesFigure);
            
            uicontrol(chooseTracesFigure,...
                'Style',                'pushbutton',                           ...
                'Units',                'pixels',                               ...
                'Position',             [figureWidth-60 10 50 25],              ...
                'String',               'OK',                                   ...
                'Callback',             @(varargin) self.chooseTraces(chooseTracesFigure)   ...
                );
        end
        
        function boxes = getTraceChoiceUIControls(~,fig)
            boxes = findobj(fig,'-regexp','Tag','(first|last)?(trace|sweep|channel)([0-9]+checkbox|slider|text)');
        end
        
        function createChoicePanel(self,fig,dims,sweepNameRegex,tagPrefix)
            delete(self.getTraceChoiceUIControls(fig));
            
            nChoices = prod(arrayfun(@(dim) size(self.TraceNames,dim),dims));
            
            if nChoices > 10
                self.createChoiceSliderPanel(fig,nChoices,tagPrefix)
            else
                self.createChoiceCheckboxPanel(fig,nChoices,dims,sweepNameRegex,tagPrefix);
            end
        end
            
        function createChoiceCheckboxPanel(self,fig,nChoices,dims,sweepNameRegex,tagPrefix)
            figurePosition = get(fig,'Position');
            figureWidth = figurePosition(3);
            figureHeight = figurePosition(4);
            
            for ii = 1:nChoices
                % TODO : this assumes TraceNames is always 3D with first
                % dimension of size 1, which is true for now...
                if isscalar(dims)
                    singleIndex = {1,1,1};
                    singleIndex{dims} = ii;
                    
                    sliceIndex = {1,':',':'};
                    sliceIndex{dims} = ii;
                else
                    singleIndex = {1,ii};
                    sliceIndex = singleIndex;
                end
                
                traceName = self.TraceNames(singleIndex{:});
                
                sweepName = regexp(traceName,sweepNameRegex,'tokens');
                
                uicontrol(fig,...
                    'Style',            'checkbox',                                                             ...
                    'Units',            'pixels',                                                               ...
                    'Position',         [20 figureHeight-70-30*ii figureWidth-40 25],                           ...
                    'String',           sweepName{1}{1},                                                        ...
                    'Tag',              sprintf('%s%dcheckbox',tagPrefix,ii),                             ...
                    'Value',            all(ismember(self.TraceNames(sliceIndex{:}),self.SelectedTraceNames))   ...
                    );
            end
        end
        
        function createChoiceSliderPanel(~,fig,nChoices,tagPrefix)
            errordlg('If you''re seeing this message, tell John to stop using the deployment repository as a development branch');
            
            figurePosition = get(fig,'Position');
            figureWidth = figurePosition(3);
            figureHeight = figurePosition(4);
            
            uicontrol(fig,                                                          ...
                'Style',        'text',                                             ...
                'String',       ['First ' upper(tagPrefix(1)) tagPrefix(2:end)],    ...
                'Tag',          sprintf('first%stextbefore',tagPrefix),             ...
                'Position',     [20 figureHeight-70-30 50 25]                       ...
                );
            
            firstSlider = uicontrol(fig,                                            ...
                'Style',        'slider',                                           ...
                'Min',          1,                                                  ...
                'Max',          nChoices-1,                                         ...
                'Value',        1,                                                  ...
                'SliderStep',   [1/(nChoices-2) 10/(nChoices-2)],                   ... 
                'Tag',          sprintf('first%sslider',tagPrefix),                 ...
                'Position',     [70 figureHeight-70-30 figureWidth-110 25]          ...
                );
            
            firstText = uicontrol(fig,                                              ...
                'Style',        'text',                                             ...
                'String',       '1',                                                ...
                'Tag',          sprintf('first%stextbefore',tagPrefix),             ...
                'Position',     [figureWidth-45 figureHeight-70-30 25 25]           ...
                );
            
            uicontrol(fig,                                                          ...
                'Style',        'text',                                             ...
                'String',       ['Last ' upper(tagPrefix(1)) tagPrefix(2:end)],     ...
                'Tag',          sprintf('last%stextbefore',tagPrefix),              ...
                'Position',     [20 figureHeight-110-30 50 25]                      ...
                );
            
            lastSlider = uicontrol(fig,                                             ...
                'Style',        'slider',                                           ...
                'Min',          2,                                                  ...
                'Max',          nChoices,                                           ...
                'Value',        nChoices,                                           ...
                'SliderStep',   [1/(nChoices-2) 10/(nChoices-2)],                   ...
                'Tag',          sprintf('last%sslider',tagPrefix),                  ...
                'Position',     [70 figureHeight-110-30 figureWidth-110 25]         ...
                );
            
            lastText = uicontrol(fig,                                              ...
                'Style',        'text',                                             ...
                'String',       num2str(nChoices),                                  ...
                'Tag',          sprintf('last%stextbefore',tagPrefix),              ...
                'Position',     [figureWidth-45 figureHeight-110-30 25 25]          ...
                );
            
            function updateSliders(thisSlider,thisText,otherSlider,otherText,nChoices)
                thisValue = round(get(thisSlider,'Value'));
                
                set(thisSlider,'Value',thisValue);
                
                if strncmpi(get(thisSlider,'Tag'),'first',5)
                    set(otherSlider,'Min',min(thisValue+1,nChoices));
                else
                    set(otherSlider,'Max',max(1,thisValue-1));
                end
                
                otherMin = get(otherSlider,'Min');
                otherMax = get(otherSlider,'Max');
                
                if otherMin == otherMax
                    set(otherSlider,'Enable','off');
                else
                    set(otherSlider,'Enable','on');
                end
                
                set(otherSlider,'SliderStep',max(0,min(1,[1 10]./(otherMax-otherMin))));
                   
                set(thisText,'String',num2str(thisValue));
                set(otherText,'String',num2str(get(otherSlider,'Value')));
            end
            
            set(firstSlider,'Callback',@(varargin) updateSliders(firstSlider,firstText,lastSlider,lastText,nChoices));
            set(lastSlider,'Callback',@(varargin) updateSliders(lastSlider,lastText,firstSlider,firstText,nChoices));
        end
            
        function createAllTracesChoicePanel(self,fig)
            self.createChoicePanel(fig,[2 3],'(.*)','trace');
        end
        
        function createSweepsChoicePanel(self,fig)
            self.createChoicePanel(fig,2,'(sweep [0-9]+)','sweep');
        end
        
        function createChannelsChoicePanel(self,fig)
            self.createChoicePanel(fig,3,'channel (.+)','channel');
        end
        
        function refreshData(self)
            selection = get(findobj(self.Figure,'Tag','dataselectionpopupmenu'),'Value');
            
            data = self.selectData(selection);
            
            cla(self.DataAxis);
            set(self.DataAxis,'XLimMode','auto');
               
            if selection < 7
                plotTraces(self.DataAxis,data,self.SampleRate,'RecordingMode',self.RecordingMode);
                return
            elseif selection < 12
                plotParams(self.DataAxis,data);
                
                switch selection
                    case 7
                        ylabel(self.DataAxis,'Series Resistance (M{\Omega})');
                    case 8
                        ylabel(self.DataAxis,'Input Resistance (M{\Omega})');
                    case 9
                        ylabel(self.DataAxis,'Membrane Time Constant (s)');
                    case 10
                        ylabel(self.DataAxis,'Membrane Capacitance (pF)');
                    case 11
                        ylabel(self.DataAxis,'Charge Transferred (pC)');
                end
                        
                return
            end
            
            % if we get here, selection == 12, i.e. show temporal parameters
            time = (1:size(data,1))/self.SampleRate;
            
            plotTraces(self.DataAxis,data,self.SampleRate,'RecordingMode',self.RecordingMode);
            
            hold(self.DataAxis,'on');
            
            start = str2double(get(findobj(self.Figure,'Tag','tpstarteditbox'),'String'));
            
            latencyHandles = line(repmat(self.Latencies+start,2,1),repmat(ylim',1,numel(self.Latencies)),'Color','k','LineStyle','-');
            peakTimeHandles = plot(time(self.PeakIndices),data(self.PeakIndices),'Color','r','LineStyle','none','Marker','o');
            riseTimeHandles = plot(time([self.Peak10IndexRising;self.Peak90IndexRising]),data([self.Peak10IndexRising;self.Peak90IndexRising]),'Color','k','LineStyle','--','Marker','o');
            fallTimeHandles = plot(time([self.Peak10IndexFalling;self.Peak90IndexFalling]),data([self.Peak10IndexFalling;self.Peak90IndexFalling]),'Color','k','LineStyle','-.','Marker','o');
            halfWidthHandles = plot(time([self.Peak50IndexRising;self.Peak50IndexFalling]),data([self.Peak50IndexRising;self.Peak50IndexFalling]),'Color','k','LineStyle',':','Marker','o');
            
            legend(self.DataAxis,[peakTimeHandles(1);latencyHandles(1);riseTimeHandles(1);fallTimeHandles(1);halfWidthHandles(1)],{'Peak' 'Latency' 'Rise Time' 'Fall Time' 'Half Width'},'Location','NorthEast');
        
            window = str2double(get(findobj(self.Figure,'Tag','tplengtheditbox'),'String')); 
            
            xlim(self.DataAxis,[start start+max(window,1/self.SampleRate)]);
        end
        
        function saveData(self)
            mc = metaclass(self);
            
            fields = mc.PropertyList;
            
            fieldsToSave = {fields(strcmpi('public',{fields.SetAccess}) & ~[fields.Constant] & ~[fields.Hidden]).Name};
            
            structToSave = struct([]);
            
            for ii = 1:numel(fieldsToSave)
                structToSave(1).(fieldsToSave{ii}) = self.(fieldsToSave{ii});
            end
            
            [saveFile,savePath] = uiputfile('*.mat');
            
            if ~ischar(saveFile)
                return
            end
            
            save([savePath saveFile],'-struct','structToSave');
        end
        
        function saveFigure(self)
            fig = figure;
            ax = axes(fig);
            pos = get(ax,'Position');
            delete(ax);
            
            ax = copyobj(self.DataAxis,fig);
            
            set(ax,'Position',pos);
            
            [saveFile,savePath] = uiputfile({'*.fig' '*.bmp' '*.emf' '*.eps' '*.hdf' '*.pbm' '*.pcx' '*.pdf' '*.pgm' '*.png' '*.ps' '*.svg' '*.tif'}');
            
            if ~ischar(saveFile)
                return
            end
            
            saveas(ax,[savePath saveFile]);
            
            close(fig);
        end
        
        function data = selectData(self,selection)
            switch selection
                case 1
                    data = self.SelectedTraces;
                case 2
                    data = self.BaselineSubtractedTraces;
                case 3
                    data = self.AverageTrace;
                case 4
                    data = self.FilteredTraces;
                case 5
                    data = self.AverageFilteredTrace;
                case 6
                    data = self.FilteredAverageTrace;
                case 7
                    data = self.SeriesResistance;
                case 8
                    data = self.InputResistance;
                case 9
                    data = self.MembraneTimeConstant;
                case 10
                    data = self.MembraneCapacitance;
                case 11
                    data = self.ChargeTransferred;
                case 12
                    data = self.selectData(get(findobj(self.Figure,'Tag','tpdatasourcepopupmenu'),'Value')); % LOLrecursion
            end
        end
        
        function updatePreprocessing(self)
            isBaselineSubtract = logical(get(findobj(self.Figure,'Tag','baselinesubtractcheckbox'),'Value'));
            
            if isBaselineSubtract
                % TODO : input checking
                baselineStart = str2double(get(findobj(self.Figure,'Tag','baselinestarteditbox'),'String'));
                baselineWindow = str2double(get(findobj(self.Figure,'Tag','baselinelengtheditbox'),'String')); 
            else
                baselineStart = 0;
                baselineWindow = 0;
            end
            
            preFilterCheckBox = findobj(self.Figure,'Tag','prefiltercheckbox');
            preFilterPopupMenu = findobj(self.Figure,'Tag','prefilterpopupmenu');
            preFilterEditBox = findobj(self.Figure,'Tag','prefiltereditbox');
            
            isPreFilter = logical(get(preFilterCheckBox,'Value'));
            
            if isPreFilter
                set([preFilterPopupMenu; preFilterEditBox],'Enable','on');
                
                switch get(preFilterPopupMenu,'Value')
                    case 1
                        preFilterFun = @mean;
                    case 2
                        preFilterFun = @median;
                end
                
                preFilterLength = round(str2double(get(preFilterEditBox,'String')));
            else
                set([preFilterPopupMenu; preFilterEditBox],'Enable','off');
                
                preFilterFun = @(x) x;
                preFilterLength = 1;
            end
            
            postFilterCheckBox = findobj(self.Figure,'Tag','postfiltercheckbox');
            postFilterPopupMenu = findobj(self.Figure,'Tag','postfilterpopupmenu');
            postFilterEditBox = findobj(self.Figure,'Tag','postfiltereditbox');
            
            isPostFilter = logical(get(postFilterCheckBox,'Value'));
            
            if isPostFilter
                set([postFilterPopupMenu; postFilterEditBox],'Enable','on');
                
                switch get(postFilterPopupMenu,'Value')
                    case 1
                        postFilterFun = @mean;
                    case 2
                        postFilterFun = @median;
                end
                
                postFilterLength = round(str2double(get(postFilterEditBox,'String')));
            else
                set([postFilterPopupMenu; postFilterEditBox],'Enable','off');
                
                postFilterFun = @(x) x;
                postFilterLength = 1;
            end
            
            [self.FilteredAverageTrace,self.AverageFilteredTrace,self.FilteredTraces,self.AverageTrace,self.BaselineSubtractedTraces,self.Baseline] = preprocess(self.SelectedTraces,self.SampleRate,'Start',baselineStart,'Window',baselineWindow,'PreFilter',isPreFilter,'PreFilterFun',preFilterFun,'PreFilterLength',preFilterLength,'PostFilter',isPostFilter,'PostFilterFun',postFilterFun,'PostFilterLength',postFilterLength);
            
            % TODO : an event driven model would make much more sense for
            % this
            self.updateCellParametersCalculation();
            self.updateTPCalculation();
            
            self.refreshData();
        end
        
        function updateRecordingMode(self,eventData)
            self.RecordingMode = eventData.NewValue.String;
            
            self.refreshData();
        end
        
        function updateCellParametersCalculation(self)
            responseStart = str2double(get(findobj(self.Figure,'Tag','rsstarteditbox'),'String'));
            responseLength = str2double(get(findobj(self.Figure,'Tag','rslengtheditbox'),'String')); 
            steadyStateStart = str2double(get(findobj(self.Figure,'Tag','ssstarteditbox'),'String'));
            steadyStateLength = str2double(get(findobj(self.Figure,'Tag','sslengtheditbox'),'String')); 
            voltageStep = str2double(get(findobj(self.Figure,'Tag','voltagestepeditbox'),'String')); 
            
            data = self.selectData(get(findobj(self.Figure,'Tag','rsdatasourcepopupmenu'),'Value'));
            
            [self.SeriesResistance,self.InputResistance,self.MembraneTimeConstant,self.MembraneCapacitance,self.SteadyStateCurrent] = calculateCellParameters(data,voltageStep,self.SampleRate,'ResponseStart',responseStart,'ResponseLength',responseLength,'SteadyStateStart',steadyStateStart,'SteadyStateLength',steadyStateLength);
            self.ChargeTransferred = calculateAUC(data,self.SampleRate,'WindowStart',responseStart,'WindowLength',steadyStateStart+steadyStateLength-responseLength,'Baseline',self.SteadyStateCurrent);
            
            self.refreshData();
        end
        
        function updateTPCalculation(self)
            start = str2double(get(findobj(self.Figure,'Tag','tpstarteditbox'),'String'));
            window = str2double(get(findobj(self.Figure,'Tag','tplengtheditbox'),'String')); 
            
            data = self.selectData(get(findobj(self.Figure,'Tag','tpdatasourcepopupmenu'),'Value'));
            
            [self.Peaks,self.PeakIndices,self.Latencies,self.RiseTimes,self.FallTimes,self.HalfWidths,self.Peak10IndexRising,self.Peak90IndexRising,self.Peak90IndexFalling,self.Peak10IndexFalling,self.Peak50IndexRising,self.Peak50IndexFalling] = calculateTemporalParameters(data,self.SampleRate,'Start',start,'Window',window);
            
            self.refreshData();
        end
    end
end