classdef BasicEphysAnalysisGUI < handle
    properties(Constant=true)
        DataOptions = {                     ...
            'Raw Traces',                   ...
            'Baseline Subtracted Traces',   ...
            'Average Trace',                ...
            'Filtered Traces',              ...
            'Average Filtered Trace',       ...
            'Filtered Average Trace',       ...
            'Series Resistance',            ...
            'Temporal Parameters',          ...
            };
    end
    
    properties(GetAccess=public,SetAccess=protected)
        Figure
        DataAxis
    end
    
    properties
        AllTraces
        TraceNames
        SelectedTraceIndices
        SelectedTraces
        Baseline
        BaselineSubtractedTraces
        AverageTrace
        FilteredTraces
        AverageFilteredTrace
        FilteredAverageTrace
        SeriesResistance
        Peaks
        PeakIndices
        Latencies
        RiseTimes
        FallTimes
        HalfWidths
        Peak10IndexRising
        Peak90IndexRising
        Peak90IndexFalling
        Peak10IndexFalling
        Peak50IndexRising
        Peak50IndexFalling
        SampleRate
        RecordingMode = 'IC'
        Filenames
    end
    
    methods
        function self = BasicEphysAnalysisGUI
            figureWidth = 1000;
            figureHeight = 500;
            self.Figure = figure('Position',[100 100 figureWidth figureHeight]);
            
            % TODO : why doesn't Matlab have decent automatic layout
            % options?  like a fucking grid layout or something jesus fuck
            self.DataAxis = subplot('Position',[245/figureWidth 50/figureHeight 540/figureWidth 400/figureHeight]);
            
            uicontrol(self.Figure,                                  ...
                'Style',    'popupmenu',                            ...
                'String',   BasicEphysAnalysisGUI.DataOptions,      ...
                'Units',    'normalized',                           ...
                'Tag',      'dataselectionpopupmenu',               ...
                'Position', [245/figureWidth 460/figureHeight 540/figureWidth 25/figureHeight],       ...
                'Callback', @(varargin) self.refreshData()          ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'pushbutton',                           ...
                'String',   'Choose Files...',                      ...
                'Units',    'normalized',                           ...
                'Position', [10/figureWidth 425/figureHeight 120/figureWidth 25/figureHeight],        ...
                'Callback', @(varargin) self.loadFiles()            ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Preprocessing:',                       ...
                'Units',    'normalized',                           ...
                'Position', [10/figureWidth 390/figureHeight 120/figureWidth 25/figureHeight],        ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uibuttongroup(self.Figure,'Position',[10/figureWidth 250/figureHeight 175/figureWidth 150/figureHeight]);
            
            uicontrol(self.Figure,                                  ...
                'Style',    'checkbox',                             ...
                'String',   'Baseline Subtract',                    ...
                'Units',    'normalized',                           ...
                'Tag',      'baselinesubtractcheckbox',             ...
                'Position', [15/figureWidth 380/figureHeight 110/figureWidth 15/figureHeight],        ...
                'Callback', @(varargin) self.updatePreprocessing()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Start (s):',                           ...
                'Units',    'normalized',                           ...
                'Position', [15/figureWidth 360/figureHeight 60/figureWidth 15/figureHeight],         ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'edit',                                 ...
                'String',   '0',                                    ...
                'Units',    'normalized',                           ...
                'Tag',      'baselinestarteditbox',                 ...
                'Position', [60/figureWidth 360/figureHeight 30/figureWidth 15/figureHeight],         ...
                'Callback', @(varargin) self.updatePreprocessing()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Length (s):',                          ...
                'Units',    'normalized',                           ...
                'Position', [90/figureWidth 360/figureHeight 60/figureWidth 15/figureHeight],         ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'edit',                                 ...
                'String',   '0.1',                                  ...
                'Units',    'normalized',                           ...
                'Tag',      'baselinelengtheditbox',                ...
                'Position', [145/figureWidth 360/figureHeight 30/figureWidth 15/figureHeight],        ...
                'Callback', @(varargin) self.updatePreprocessing()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'checkbox',                             ...
                'String',   'Filter Before Averaging:',             ...
                'Units',    'normalized',                           ...
                'Tag',      'prefiltercheckbox',                    ...
                'Position', [15/figureWidth 340/figureHeight 150/figureWidth 15/figureHeight],        ...
                'Callback', @(varargin) self.updatePreprocessing()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'popupmenu',                            ...
                'String',   {                                       ...
                    'Mean',                                         ...
                    'Median'                                        ...
                    },                                              ...
                'Units',    'normalized',                           ...
                'Tag',      'prefilterpopupmenu',                   ...
                'Position', [15/figureWidth 310/figureHeight 75/figureWidth 25/figureHeight],         ...
                'Callback', @(varargin) self.updatePreprocessing()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Length:',                              ...
                'Units',    'normalized',                           ...
                'Position', [95/figureWidth 315/figureHeight 50/figureWidth 15/figureHeight],         ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'edit',                                 ...
                'String',   '3',                                    ...
                'Units',    'normalized',                           ...
                'Tag',      'prefiltereditbox',                     ...
                'Position', [140/figureWidth 315/figureHeight 40/figureWidth 15/figureHeight],        ...
                'Callback', @(varargin) self.updatePreprocessing()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'checkbox',                             ...
                'String',   'Filter After Averaging:',              ...
                'Units',    'normalized',                           ...
                'Tag',      'postfiltercheckbox',                   ...
                'Position', [15/figureWidth 295/figureHeight 150/figureWidth 15/figureHeight],        ...
                'Callback', @(varargin) self.updatePreprocessing()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'popupmenu',                            ...
                'String',   {                                       ...
                    'Mean',                                         ...
                    'Median'                                        ...
                    },                                              ...
                'Units',    'normalized',                           ...
                'Tag',      'postfilterpopupmenu',            ...
                'Position', [15/figureWidth 265/figureHeight 75/figureWidth 25/figureHeight],         ...
                'Callback', @(varargin) self.updatePreprocessing()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Length:',                              ...
                'Units',    'normalized',                           ...
                'Position', [95/figureWidth 270/figureHeight 50/figureWidth 15/figureHeight],         ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'edit',                                 ...
                'String',   '3',                                    ...
                'Units',    'normalized',                           ...
                'Tag',      'postfiltereditbox',                    ...
                'Position', [140/figureWidth 270/figureHeight 40/figureWidth 15/figureHeight],        ...
                'Callback', @(varargin) self.updatePreprocessing()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Series Resistance Calculation:',       ...
                'Units',    'normalized',                           ...
                'Position', [10/figureWidth 220/figureHeight 180/figureWidth 25/figureHeight],        ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uibuttongroup(self.Figure,'Position',[10/figureWidth 150/figureHeight 175/figureWidth 80/figureHeight]);
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Using:',                               ...
                'Units',    'normalized',                           ...
                'Position', [15/figureWidth 205/figureHeight 35/figureWidth 15/figureHeight],         ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'popupmenu',                            ...
                'String',   BasicEphysAnalysisGUI.DataOptions(1:6), ...
                'Units',    'normalized',                           ...
                'Tag',      'rsdatasourcepopupmenu',                ...
                'Position', [50/figureWidth 210/figureHeight 130/figureWidth 15/figureHeight],        ...
                'Callback', @(varargin) self.updateRSCalculation()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Voltage Step (V):',                    ...
                'Units',    'normalized',                           ...
                'Position', [15/figureWidth 180/figureHeight 100/figureWidth 15/figureHeight],        ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'edit',                                 ...
                'String',   '-5',                                   ...
                'Units',    'normalized',                           ...
                'Tag',      'voltagestepeditbox',                   ...
                'Position', [110/figureWidth 180/figureHeight 30/figureWidth 15/figureHeight],        ...
                'Callback', @(varargin) self.updateRSCalculation()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Start (s):',                           ...
                'Units',    'normalized',                           ...
                'Position', [15/figureWidth 155/figureHeight 60/figureWidth 15/figureHeight],         ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'edit',                                 ...
                'String',   '0',                                    ...
                'Units',    'normalized',                           ...
                'Tag',      'rsstarteditbox',                       ...
                'Position', [60/figureWidth 155/figureHeight 30/figureWidth 15/figureHeight],         ...
                'Callback', @(varargin) self.updateRSCalculation()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Length (s):',                          ...
                'Units',    'normalized',                           ...
                'Position', [90/figureWidth 155/figureHeight 60/figureWidth 15/figureHeight],         ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'edit',                                 ...
                'String',   '0.1',                                  ...
                'Units',    'normalized',                           ...
                'Tag',      'rslengtheditbox',                      ...
                'Position', [145/figureWidth 155/figureHeight 30/figureWidth 15/figureHeight],        ...
                'Callback', @(varargin) self.updateRSCalculation()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Temporal Parameters Calculation:',     ...
                'Units',    'normalized',                           ...
                'Position', [10/figureWidth 120/figureHeight 180/figureWidth 25/figureHeight],        ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uibuttongroup(self.Figure,'Position',[10/figureWidth 75/figureHeight 175/figureWidth 55/figureHeight]);
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Using:',                               ...
                'Units',    'normalized',                           ...
                'Position', [15/figureWidth 105/figureHeight 35/figureWidth 15/figureHeight],         ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'popupmenu',                            ...
                'String',   BasicEphysAnalysisGUI.DataOptions(1:6), ...
                'Units',    'normalized',                           ...
                'Tag',      'tpdatasourcepopupmenu',                ...
                'Position', [50/figureWidth 110/figureHeight 130/figureWidth 15/figureHeight],        ...
                'Callback', @(varargin) self.updateTPCalculation()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Start (s):',                           ...
                'Units',    'normalized',                           ...
                'Position', [15/figureWidth 80/figureHeight 60/figureWidth 15/figureHeight],         ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'edit',                                 ...
                'String',   '0',                                    ...
                'Units',    'normalized',                           ...
                'Tag',      'tpstarteditbox',                       ...
                'Position', [60/figureWidth 80/figureHeight 30/figureWidth 15/figureHeight],         ...
                'Callback', @(varargin) self.updateTPCalculation()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Length (s):',                          ...
                'Units',    'normalized',                           ...
                'Position', [90/figureWidth 80/figureHeight 60/figureWidth 15/figureHeight],         ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'edit',                                 ...
                'String',   '0.1',                                  ...
                'Units',    'normalized',                           ...
                'Tag',      'tplengtheditbox',                      ...
                'Position', [145/figureWidth 80/figureHeight 30/figureWidth 15/figureHeight],        ...
                'Callback', @(varargin) self.updateTPCalculation()  ...
                );
            
            uicontrol(self.Figure,                                  ...
                'Style',    'text',                                 ...
                'String',   'Recording Mode:',                      ...
                'Units',    'normalized',                           ...
                'Position', [10/figureWidth 45/figureHeight 180/figureWidth 25/figureHeight],         ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            recordModeButtonGroup = uibuttongroup(self.Figure,      ...
                'Position', [10/figureWidth 20/figureHeight 175/figureWidth 35/figureHeight],         ...
                'SelectionChangedFcn',  @(~,eventData,varargin) self.updateRecordingMode(eventData)  ...
                );
            
            uicontrol(recordModeButtonGroup,                        ...
                'Style',    'radiobutton',                          ...
                'String',   'IC',                                   ...
                'Tag',      'currentclampradiobutton',              ...
                'Units',    'normalized',                           ...
                'Position', [5/175 5/35 75/175 25/35],              ...
                'HorizontalAlignment',  'left'                      ...
                );
            
            uicontrol(recordModeButtonGroup,                        ...
                'Style',    'radiobutton',                          ...
                'String',   'VC',                                   ...
                'Units',    'normalized',                           ...
                'Position', [95/175 5/35 75/175 25/35],             ...
                'HorizontalAlignment',  'left'                      ...
                );
            
%             uipanel(self.Figure,               ...
%                 'BackgroundColor',  'w',                            ...
%                 'Tag',      'filelistouterpanel',                   ...
%                 'Position', [800/figureWidth 10/figureHeight 190/figureWidth 480/figureHeight]);
%             
%             uipanel(self.Figure,               ...
%                 'BackgroundColor',  'w',                            ...
%                 'BorderType',       'none',                         ...
%                 'Tag',      'filelistinnerpanel',                   ...
%                 'Position', [830/figureWidth 22/figureHeight 158/figureWidth 464/figureHeight]);
%             
%             uicontrol(recordModeButtonGroup,                        ...
%                 'Style',    'slider',                               ...
%                 'Value',    0,                                      ...
%                 'Units',    'normalized',                           ...
%                 'Position', [800/figureWidth 5/35 75/175 25/35]             ...
%                 );
        end
        
        function delete(self)
            delete(self.Figure)
        end
        
        function loadFiles(self)
            self.Filenames = uigetfile('*.xsg;*.h5','MultiSelect','on'); % TODO : will we ever want to combine files from multiple folders?  Might make sense to switch to uipickfiles
    
            if isnumeric(self.Filenames)
                return
            end

            if ischar(self.Filenames)
                self.Filenames = {self.Filenames};
            end
    
            [self.AllTraces,self.SampleRate,self.TraceNames] = concatenateTraces(self.Filenames);
            
            self.SelectedTraceIndices = 1:(size(self.AllTraces,2)*size(self.AllTraces,3));
            
            self.SelectedTraces = self.AllTraces(:,self.SelectedTraceIndices);
            
            for ii = 1:numel(self.TraceNames)
                disp(self.TraceNames{ii});
            end
            
            self.updatePreprocessing();
        end
        
        function refreshData(self)
            selection = get(findobj(self.Figure,'Tag','dataselectionpopupmenu'),'Value');
            
            data = self.selectData(selection);
            
            cla(self.DataAxis);
            set(self.DataAxis,'XLimMode','auto');
               
            if selection < 7
                plotTraces(self.DataAxis,data,self.SampleRate,'RecordingMode',self.RecordingMode);
                return
            elseif selection == 7
                plotParams(self.DataAxis,data);
                return
            end
            
            % if we get here, selection == 8, i.e. show temporal parameters
            time = (1:size(data,1))/self.SampleRate;
            
            plotTraces(self.DataAxis,data,self.SampleRate,'RecordingMode',self.RecordingMode);
            
            hold(self.DataAxis,'on');
            
            start = str2double(get(findobj(self.Figure,'Tag','tpstarteditbox'),'String'));
            
            latencyHandles = line(repmat(self.Latencies+start,2,1),repmat(ylim',1,numel(self.Latencies)),'Color','k','LineStyle','-');
            peakTimeHandles = plot(time(self.PeakIndices),data(self.PeakIndices),'Color','r','LineStyle','none','Marker','o');
            riseTimeHandles = plot(time([self.Peak10IndexRising;self.Peak90IndexRising]),data([self.Peak10IndexRising;self.Peak90IndexRising]),'Color','k','LineStyle','--','Marker','o');
            fallTimeHandles = plot(time([self.Peak10IndexFalling;self.Peak90IndexFalling]),data([self.Peak10IndexFalling;self.Peak90IndexFalling]),'Color','k','LineStyle','-.','Marker','o');
            halfWidthHandles = plot(time([self.Peak50IndexRising;self.Peak50IndexFalling]),data([self.Peak50IndexRising;self.Peak50IndexFalling]),'Color','k','LineStyle',':','Marker','o');
            
            legend(self.DataAxis,[peakTimeHandles(1);latencyHandles(1);riseTimeHandles(1);fallTimeHandles(1);halfWidthHandles(1)],{'Peak' 'Latency' 'Rise Time' 'Fall Time' 'Half Width'},'Location','NorthEast');
        
            window = str2double(get(findobj(self.Figure,'Tag','tplengtheditbox'),'String')); 
            
            xlim(self.DataAxis,[start start+max(window,1/self.SampleRate)]);
        end
        
        function data = selectData(self,selection)
            switch selection
                case 1
                    data = self.SelectedTraces;
                case 2
                    data = self.BaselineSubtractedTraces;
                case 3
                    data = self.AverageTrace;
                case 4
                    data = self.FilteredTraces;
                case 5
                    data = self.AverageFilteredTrace;
                case 6
                    data = self.FilteredAverageTrace;
                case 7
                    data = self.SeriesResistance;
                case 8
                    data = self.selectData(get(findobj(self.Figure,'Tag','tpdatasourcepopupmenu'),'Value')); % LOLrecursion
            end
        end
        
        function updatePreprocessing(self)
            isBaselineSubtract = logical(get(findobj(self.Figure,'Tag','baselinesubtractcheckbox'),'Value'));
            
            if isBaselineSubtract
                % TODO : input checking
                baselineStart = str2double(get(findobj(self.Figure,'Tag','baselinestarteditbox'),'String'));
                baselineWindow = str2double(get(findobj(self.Figure,'Tag','baselinelengtheditbox'),'String')); 
            else
                baselineStart = 0;
                baselineWindow = 0;
            end
            
            preFilterCheckBox = findobj(self.Figure,'Tag','prefiltercheckbox');
            preFilterPopupMenu = findobj(self.Figure,'Tag','prefilterpopupmenu');
            preFilterEditBox = findobj(self.Figure,'Tag','prefiltereditbox');
            
            isPreFilter = logical(get(preFilterCheckBox,'Value'));
            
            if isPreFilter
                set([preFilterPopupMenu; preFilterEditBox],'Enable','on');
                
                switch get(preFilterPopupMenu,'Value')
                    case 1
                        preFilterFun = @mean;
                    case 2
                        preFilterFun = @median;
                end
                
                preFilterLength = round(str2double(get(preFilterEditBox,'String')));
            else
                set([preFilterPopupMenu; preFilterEditBox],'Enable','off');
                
                preFilterFun = @(x) x;
                preFilterLength = 1;
            end
            
            postFilterCheckBox = findobj(self.Figure,'Tag','postfiltercheckbox');
            postFilterPopupMenu = findobj(self.Figure,'Tag','postfilterpopupmenu');
            postFilterEditBox = findobj(self.Figure,'Tag','postfiltereditbox');
            
            isPostFilter = logical(get(postFilterCheckBox,'Value'));
            
            if isPostFilter
                set([postFilterPopupMenu; postFilterEditBox],'Enable','on');
                
                switch get(postFilterPopupMenu,'Value')
                    case 1
                        postFilterFun = @mean;
                    case 2
                        postFilterFun = @median;
                end
                
                postFilterLength = round(str2double(get(postFilterEditBox,'String')));
            else
                set([postFilterPopupMenu; postFilterEditBox],'Enable','off');
                
                postFilterFun = @(x) x;
                postFilterLength = 1;
            end
            
            [self.FilteredAverageTrace,self.AverageFilteredTrace,self.FilteredTraces,self.AverageTrace,self.BaselineSubtractedTraces,self.Baseline] = preprocess(self.SelectedTraces,self.SampleRate,'Start',baselineStart,'Window',baselineWindow,'PreFilter',isPreFilter,'PreFilterFun',preFilterFun,'PreFilterLength',preFilterLength,'PostFilter',isPostFilter,'PostFilterFun',postFilterFun,'PostFilterLength',postFilterLength);
            
            % TODO : an event driven model would make much more sense for
            % this
            self.updateRSCalculation();
            self.updateTPCalculation();
            
            self.refreshData();
        end
        
        function updateRecordingMode(self,eventData)
            self.RecordingMode = eventData.NewValue.String;
            
            self.refreshData();
        end
        
        function updateRSCalculation(self)
            start = str2double(get(findobj(self.Figure,'Tag','rsstarteditbox'),'String'));
            window = str2double(get(findobj(self.Figure,'Tag','rslengtheditbox'),'String')); 
            voltageStep = str2double(get(findobj(self.Figure,'Tag','voltagestepeditbox'),'String')); 
            
            data = self.selectData(get(findobj(self.Figure,'Tag','rsdatasourcepopupmenu'),'Value'));
            
            [self.SeriesResistance] = calculateSeriesResistance(data,self.SampleRate,'Start',start,'Window',window,'VoltageStep',voltageStep);
            
            self.refreshData();
        end
        
        function updateTPCalculation(self)
            start = str2double(get(findobj(self.Figure,'Tag','tpstarteditbox'),'String'));
            window = str2double(get(findobj(self.Figure,'Tag','tplengtheditbox'),'String')); 
            
            data = self.selectData(get(findobj(self.Figure,'Tag','tpdatasourcepopupmenu'),'Value'));
            
            [self.Peaks,self.PeakIndices,self.Latencies,self.RiseTimes,self.FallTimes,self.HalfWidths,self.Peak10IndexRising,self.Peak90IndexRising,self.Peak90IndexFalling,self.Peak10IndexFalling,self.Peak50IndexRising,self.Peak50IndexFalling] = calculateTemporalParameters(data,self.SampleRate,'Start',start,'Window',window);
            
            self.refreshData();
        end
    end
end